version: "3"
networks:
    vteam6:
      driver: bridge
services:
    database:
      container_name: vteam6_database
      image: mariadb:latest
      restart: always
      volumes:
        - ./database/sql:/docker-entrypoint-initdb.d
      environment:
        MYSQL_ROOT_PASSWORD: ${ROOT_PASS}
        MYSQL_DATABASE: vteam
        MYSQL_USER: user
        MYSQL_PASSWORD: ${USER_PASS}
      ports:
        - "3306:3306"
      expose:
        - "3306:3306"
      networks:
            vteam6:
      # Test the database by excuting: docker exec -it database mariadb -uroot -p
      
    server:
      container_name: "vteam6_server"
      build:
        context: ./server
        # dockerfile: ./server/Dockerfile
      ports:
          - "1337:1337"
      expose:
          - "1337:1337"
      networks:
          vteam6:
      environment:
        MYSQL_ROOT_PASSWORD: ${ROOT_PASS}
        MYSQL_DATABASE: vteam
        MYSQL_USER: user
        MYSQL_PASSWORD: ${USER_PASS}
        # MYSQL_CONNECTION_LIMIT: 20
      depends_on:
        - database
      restart:
          "always"

    admin-interface: 
      container_name: "vteam6_admin_interface"
      build:
        context: ./admin-interface
        # dockerfile: ./admin-interface/Dockerfile
      ports:
          - "1338:1338"
      expose:
          - "1338:1338"
      networks:
          vteam6:

    customer-interface: 
      container_name: "vteam6_customer_interface"
      build:
        context: ./customer-interface
        # dockerfile: ./customer-interface/Dockerfile
      ports:
          - "1339:1339"
      expose:
          - "1339:1339"
      networks:
          vteam6:

    # customer-app: 
    #   container_name: "vteam6_customer_app"
    #   build:
    #     context: ./customer-app
    #     # dockerfile: ./customer-app/Dockerfile
    #   ports:
    #       - "1340:1340"
    #   expose:
    #       - "1340:1340"
    #   networks:
    #       vteam6:

    simulation: 
      container_name: "vteam6_simulation"
      build:
        context: ./simulation
        # dockerfile: ./simulation/Dockerfile
      ports:
          - "1341:1341"
      expose:
          - "1341:1341"
      networks:
          vteam6:
