version: "3"
networks:
    vteam6:
      driver: bridge
services:
    database:
      container_name: vteam6_database
      image: mariadb:latest
      restart: always
      volumes:
        - ./database/sql:/docker-entrypoint-initdb.d
      environment:
        MYSQL_ROOT_PASSWORD: ${ROOT_PASS}
        MYSQL_DATABASE: vteam
        MYSQL_USER: user
        MYSQL_PASSWORD: ${USER_PASS}
      ports:
        - "3306:3306"
      expose:
        - "3306:3306"
      networks:
            vteam6:
      # Test the database by excuting: docker exec -it database mariadb -uroot -p
      
    server:
      # image: "mrrobin/vteam6-server:0.1.0"
      # volumes:
      #     - "./server-data:/data"
      container_name: "vteam6_server"
      build:
        context: ./server
        # dockerfile: ./server/Dockerfile
      ports:
          - "1337:1337"
      expose:
          - "1337:1337"
      networks:
          vteam6:
      environment:
        MYSQL_ROOT_PASSWORD: ${ROOT_PASS}
        MYSQL_DATABASE: vteam
        MYSQL_USER: user
        MYSQL_PASSWORD: ${USER_PASS}
        # MYSQL_CONNECTION_LIMIT: 20
      depends_on:
        - database
      restart:
          "always"

    admin-interface: 
      container_name: "vteam6_admin_interface"
      build:
        context: ./admin-interface
        # dockerfile: ./admin-interface/Dockerfile
      ports:
          - "1338:1338"
      expose:
          - "1338:1338"
      networks:
          vteam6:

    # webbclient:
    #     image: "mrrobin/vteam6-webbclient:0.1.0"
    #     container_name: "vteam6_webbclient"
    #     ports:
    #         - "1338:1338"
    #     networks:
    #         vteam6:
    #     links:
    #         - "server:vteam6_server"

    # client:
    #     image: "mrrobin/vteam6-client:0.1.0"
    #     container_name: "vteam6_client"
    #     networks:
    #         vteam6:
    #     links:
    #         - "server:vteam6_server"
