name: database CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest


  #build:

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker-compose up database
    #services:
      #mariadb:
       # image: mariadb:latest
       # env:
       #   MYSQL_ROOT_PASSWORD: root_password
       #   MYSQL_DATABASE: test_database
       #   MYSQL_USER: test_user
       #   MYSQL_PASSWORD: test_password
       # ports:
       #   - 3306:3306
       # options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
        #container_name: vteam6_database
        #image: mariadb:latest
        #restart: always
        #volumes:
        #  - ./database/sql:/docker-entrypoint-initdb.d
        #environment:
        #  MYSQL_ROOT_PASSWORD: ${ROOT_PASS}
        #  MYSQL_DATABASE: vteam
        #  MYSQL_USER: user
        #  MYSQL_PASSWORD: ${USER_PASS}
       # ports:
        #  - "3306:3306"
        #expose:
        #  - "3306:3306"
        #networks:
        #      vteam6:

    #steps:
     # - name: Checkout Repository
      #  uses: actions/checkout@v2

      #- name: Setup MariaDB
      #  run: |
      #    sleep 10  # Wait for MariaDB to start
      #    mysql -h 127.0.0.1 -u test_user -ptest_password -e "SHOW DATABASES;"

      # Add more steps for testing, such as running database migrations and tests.

  # Add more jobs for additional workflows, like deployment, if needed.
