# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: server CI

on:
  push:
    branches: [ "development" ]
  pull_request:
    branches: [ "development" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        
   # - run: npm ci
   # - run: npm run build --if-present
   # - run: npm test

    - run: npm install
      working-directory: ./server
      
    - run: cat ./server/.eslintrc.js

    - run: npm run lint -- --config=/.eslintrc.js
      working-directory: ./server

    - run: npm run test
      working-directory: ./server


    # - name: Install, Build, and Test
    #   run: |
    #     for app in */; do
    #       if [ "$app" != "database/" ]; then
    #         cd "$app"
    #         printf "$app\ n"
    #         npm ci
    #         npm run build --if-present
    #         npm test
    #         cd ..
    #       fi
    #     done
